db.url=jdbc:mysql://localhost:3306/minimarket_yuly?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
db.username=root
db.password=$onamY12
db.driver=com.mysql.cj.jdbc.Driver
